automatically publish release when a new 'v*' tag pushed

diff --git a/.github/workflows/github-actions-CI.yml b/.github/workflows/github-actions-CI.yml
--- a/.github/workflows/github-actions-CI.yml
+++ b/.github/workflows/github-actions-CI.yml
@@ -2,15 +2,17 @@ name: CI
 on:
   push:
     branches:
-      - master
+      - ci-improvements
   pull_request:
     branches:
-      - master
+      - ci-improvements
 
 jobs:
-  build:
+  ci:
     name: test
     runs-on: ubuntu-latest
+    env:
+      PUBLISH_TOKEN: ${{ secret.PUBLISH }}
 
     steps:
       - name: Checkout repository
@@ -27,3 +29,36 @@ jobs:
 
       - name: Run tests
         run: ./gradlew test
+
+      - name: Has to be published?
+        id: is_release
+        if: &is_new_release ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          version="${{GITHUB_REF#refs/tags/}}"
+          version-number="${version:1}"
+          zip=./build/distributions/Decorate.me-${ version-number }.zip
+          echo "New version ${GITHUB_REF#refs/tags/} has to be published"
+
+      - name: Assembles a plugin and prepares ZIP archive for deployment
+        if: *is_new_release
+        run: ./gradle buildPlugin
+
+      - name: Check version
+        if: *is_new_release
+        run: |
+          if [ ! -f $ {{steps.is_release.outputs.zip}} ]; then
+            echo "Error: Wrong release version! Check if your tag matches with an actual version in build.gradle.kts"
+            echo "provided tag's version: ${{ steps.is_release.outputs.version-number }}"
+            echo "${{ steps.is_release.outputs.zip }} file expected to be generated"
+            echo "but actual was:"
+            ls ./build/distributions
+            exit 1
+          fi
+
+      - name: Publish GitHub Release
+        if: *is_new_release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: ${{ steps.is_release.outputs.zip }}
+
+
